version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
      - product-service
    environment:
      - JWT_SECRET=SECRET
    networks:
      - backend

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=freddy
      - POSTGRES_PASSWORD=pass@123
    networks:
      - backend
    depends_on:
      - auth-db

  auth-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=freddy
      - POSTGRES_PASSWORD=pass@123
      - POSTGRES_DB=auth-db
    ports:
      - "5433:5432"
    networks:
      - backend

  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    depends_on:
      - product-db
    environment:
      - DATABASE_URL=postgresql://freddy:pass@123@product-db:5432/marketplace?schema=public
    networks:
      - backend

  product-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=freddy
      - POSTGRES_PASSWORD=pass@123
      - POSTGRES_DB=marketplace
    ports:
      - "5434:5432"
    networks:
      - backend

networks:
  backend:
